server:
  port: 10010
spring:
  application:
    name: ly-api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1  #ip地址

ribbon:
  ConnectTimeout: 500  # 添加路由前缀
  ReadTimeout: 2500  # 通信超时时间
  OkToRetryOnAllOperations: true #是否对所有操作重试
  MaxAutoRetriesNextServer: 1  #同一服务不同实例的重试次数
  MaxAutoRetries: 1  #同一实例的重试次数
  okhttp:
    enabled: true

hystrix:
  command:
     default:
       execution:
         isolation:
           thread:
             timeoutInMillisecond: 13000  #熔断超时时长

zuul:
  prefix: /api
  retryable: true
  routes:
    item-service: /item/**
    upload-serivce:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false