server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 10MB   #最小
      max-request-size: 30MB  #最大

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 40

fdfs:
  so-timeout: 3000  #等待时长
  connect-timeout: 2000
  tracker-list:
  - 192.168.0.110:22122

leyou:
  upload:
    base_url: http://image.leyou.com
    allow_img-list:
      - image/png
      - image/jpeg
      - image/gif