server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leyoudb
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 10  #每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 40  #10秒 不发送就过期


